### ISSUE TITLE
Feature: Add and remove choice on in the runtime

### ISSUE THREAD

**Issue by ahmedshafik** [mroth/weightedrand#18] opened 2022-04-29 22:57 UTC
Hey,

I Just wanted to know if you can add a feature to add, remove choice in the run time without creating new choise everytime.

something like 
```
	Choice := wr.NewChoice("hahaha", 50)
	chooser.Add(Choice)
```

**Comment by mroth** [comment] 2022-04-29 23:51
I believe this is a duplicate of #11.  With the current algorithm used, adding or removing a choice would require regeneration of the chooser weights, which eliminates the performance invariants of the library.

I'm going to close this for now as not possible. However, if you know of a way to efficiently handle this algorithmically without an API change that I am unaware of; please feel free to re-open and document. Thanks!

**Closed by mroth** 2022-04-29 23:51 UTC
